### ISSUE TITLE
Fix formMachine issues on the object root page

### ISSUE THREAD

**Issue by BelgianNoise** [netwerk-digitaal-erfgoed/solid-crs#258]
- [x] input field on the object page will show 'undefined' instead of '' until the formMachine is created by clicking a field
- [x] At the moment, after saving the formMachine will shut itself down and no more changes can be made without refreshing and revisiting the page. We also don't want that.

**Comment by BelgianNoise** [comment]
I suggest that the Object overview page should always be in EDIT mode.
At the moment, after saving the formMachine will shut itself down and no more changes can be made without refreshing and revisiting the page. We also don't want that.

**Comment by lem-onade** [comment]
> I suggest that the Object overview page should always be in EDIT mode.

Agreed, IDLE should invoke the form machine.
