### ISSUE TITLE
Support routing in the manage application

### ISSUE THREAD

**Issue by wouteraj** [netwerk-digitaal-erfgoed/solid-crs#28]
┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=674725436) by [Unito](https://www.unito.io)

**Comment by ddeboer** [comment]
This has some priority, because without routing:

- the browser’s back button behaviour is broken
- force-refreshing any page takes the user back to the log in page.

**Comment by sdevalk** [comment]
Same as https://github.com/netwerk-digitaal-erfgoed/solid-crs/issues/404?
