### ISSUE TITLE
Confirmation before deleting a collection

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/solid-crs#298]
If I hit the 'delete' button in order to delete a collection, the collection is deleted instantly. Is it possible to display a confirmation message first?

![no_confirmation_when_deleting_collection](https://user-images.githubusercontent.com/606948/122070568-5e240580-cdf6-11eb-95ef-c1a66f35d7b9.png)

**Comment by lem-onade** [comment]
Agreed, was something we discussed earlier: https://github.com/netwerk-digitaal-erfgoed/solid-crs/issues/218

**Comment by sdevalk** [comment]
Perfect! I'll close this issue then.

**Comment by lem-onade** [comment]
I'll include the confirmation for object in https://github.com/netwerk-digitaal-erfgoed/solid-crs/issues/218, and close https://github.com/netwerk-digitaal-erfgoed/solid-crs/issues/299 as well if that's alright with you?

**Comment by sdevalk** [comment]
Excellent!
