### ISSUE TITLE
Save button isn't always visible when editing fields

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/solid-crs#302]
The 'save' button doesn't always appear when entering values in a field. See the attached screenshot: I've entered '123' in field 'Diepte', but the button is invisible.

![save_button_does_not_appear_when_fillingin_field](https://user-images.githubusercontent.com/606948/122072237-ae4f9780-cdf7-11eb-8647-bd6345a66aba.png)

**Comment by lem-onade** [comment]
This behaviour should have been fixed by https://github.com/netwerk-digitaal-erfgoed/solid-crs/pull/286. Did this object already exist before or is it a newly created one? If it already existed: could you try creating a new object and replicating with that?

**Comment by sdevalk** [comment]
Good one! The object probably already existed. I cannot reproduce the issue when adding a new object. I'll close it.
