### ISSUE TITLE
Requests made with Inrupt SDK lose authentication information after some time

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/solid-crs#315]
When using Solid CRS, at some point the error message `Er ging iets mis` appears, out of the blue. Perhaps my login session has expired? Is it possible to display a bit more descriptive error message instead?

![session-expired-but-unclear-error](https://user-images.githubusercontent.com/606948/122080006-35077300-cdfe-11eb-8a13-b8bc13494ee8.png)

**Comment by lem-onade** [comment]
Can confirm that after some time, the requests stop including have `Authorization` or `DPoP` headers.

**Comment by lem-onade** [comment]
https://github.com/inrupt/solid-client-authn-js/blob/main/CHANGELOG.md#browser
