### ISSUE TITLE
Login succeeds but leads to an invalid session

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/solid-crs#323]
I had problems with my login session multiple times which in the end leads to the message "Er ging iets fout" which resulted in the losing the entered data. I would expect an earlier warning in this case. Why the login fails is unclear to me, it sometimes works and sometimes fails... 

![afbeelding](https://user-images.githubusercontent.com/8688107/122276770-6b6bed80-cee5-11eb-9701-70c0c2aeb4d6.png)

**Comment by lem-onade** [comment]
I will be closing this issue as I believe it is a duplicate of https://github.com/netwerk-digitaal-erfgoed/solid-crs/issues/315. Feel free to re-open if I was wrong.
