### ISSUE TITLE
add CONTRIBUTING.md

### ISSUE THREAD

**Issue by raboof** [netwerk-digitaal-erfgoed/solid-crs#367]
As a new contributor it'd be useful to have a quick overview of how you'd like to receive contributions. Things like: start from the `develop` branch and PR to that, use conventional commit messages - anything else you'd like to see?

It's entirely possible that this is already documented somewhere and I just didn't find it :). A CONTRIBUTING.md file in the root of the project is a nice place to either add this information, or a link to the right place.

**Comment by lem-onade** [comment]
Hey @raboof. I opened PR #393 for this just now. Did you encounter anything else that is not listed, but people should know? Would love to hear your input.

**Comment by raboof** [comment]
Do we close this as soon as it's merged to `develop` (i.e. now) or do we wait until it makes it into master / a release?
