### ISSUE TITLE
Change title on landing page to "Collectieregistratiesysteem" 

### ISSUE THREAD

**Issue by johannadm** [netwerk-digitaal-erfgoed/solid-crs#382]
- [ ] Change the title on the landing page from "Collectieregistratiesysteem"

**Comment by sdevalk** [comment]
Or use 'Collectieregistratiesysteem' (https://github.com/netwerk-digitaal-erfgoed/solid-crs/issues/403)? The title 'Solid CRS' has a somewhat technical connotation (Solid is the underlying technology) that may not be clear to average users?
