### ISSUE TITLE
Switching to the Network-of-Terms interface causes loss of unsaved edits

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/solid-crs#399]
If you switch to the Network-of-Terms interface in the process of editing the metadata of an object the previous edits are lost when they are not saved first.

**Comment by sdevalk** [comment]
Same as https://github.com/netwerk-digitaal-erfgoed/solid-crs/issues/362?

**Comment by lem-onade** [comment]
Closing, duplicate of #362
