### ISSUE TITLE
Using a low res image leads to unclear behavior

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/solid-crs#401]
When changing the image to one with a low resolution like https://www.ennomeijers.nl/img/mondharp5-thumb.png the record can not be saved but there is no error message or warning.

**Comment by lem-onade** [comment]
Could not reproduce, works as it should on my end
![image](https://user-images.githubusercontent.com/32491056/128704171-24ca4577-c66b-423f-a335-516f799603ad.png)
![image](https://user-images.githubusercontent.com/32491056/128704191-03c1d05a-f25f-4fe1-a696-1be3615501c4.png)

Perhaps related to https://github.com/netwerk-digitaal-erfgoed/solid-crs/issues/315?

**Comment by EnnoMeijers** [comment]
Indeed this works fine now for me too, probably related to something like in #315. I'll close this issue.
