### ISSUE TITLE
Object description form: show sources of licenses

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/solid-crs#414]
In the object description form a collection manager must choose a 'Licentie'. The pulldown with the available licenses, however, doesn't make clear what the sources of the licenses are, e.g. which frameworks are used. A manager could pick the wrong license because the license names of the sources are quite similar.

Is it possible to add these sources to the label licenses (e.g. not 'Auteursrechtelijk beschermd' but 'RightsStatements.org: Auteursrechtelijk beschermd')?

![Screenshot 2021-08-09 at 09 27 38](https://user-images.githubusercontent.com/606948/128672901-1ecbeae5-9088-4757-8574-b0310c04cc78.png)

- [x] Edit existing translations for licenses

**Comment by lem-onade** [comment]
This seems to be missing from the presentation app
