### ISSUE TITLE
Support for using terms from a local/own terminology source

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/solid-crs#416]
Solid CRS currently allows collection managers to search for terms in terminology sources, using the Network of Terms. However, it's likely that managers cannot find all terms in these sources (e.g. the name of a painter that is not commonly known and therefore is not in scope of terminology sources). In this case the managers should be able to store their own terms in Solid CRS. This allows them to use these terms similar to how they use terms from terminology sources.

This has some implications:

1. Solid CRS should be able to save and retrieve terms (in addition to how it currently saves and retrieves object descriptions).
2. Solid CRS should be able to search for terms in both the Network of Terms and in the 'local dataset' with terms (e.g. when a collection manager is creating a new object description).

This feature requires further fine-tuning.

**Comment by ddeboer** [comment]
Smallest possible solution: the ability to store literals as well in the current term fields. They can be stored in the RDF in the same way as terms are now, expect their URI, which will be an internal one.
