### ISSUE TITLE
Configure subdomain for presentation module

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/solid-crs#444]
Possibly solid-crs-presentatie.netwerkdigitaalerfgoed.nl. I requested a DNS change via @EnnoMeijers.

**Comment by EnnoMeijers** [comment]
The subdomain for **solid-crs-presentatie** has been created!

**Comment by ddeboer** [comment]
Configured in https://github.com/netwerk-digitaal-erfgoed/infrastructure/pull/27. @lem-onade Can you verify that the new domain https://solid-crs-presentatie.netwerkdigitaalerfgoed.nl works correctly? (It throws an error if you visit it without any parameters, but that’s probably because a pod URL is required?)
