### ISSUE TITLE
Show all object types in grid view

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/solid-crs#471]
Currently only the (alphabetically) first type is shown; it would be better to show all types, separated by comma.

**Comment by lem-onade** [comment]
To keep the size of the grid items consistent, the types would have to fit on the same line.

![image](https://user-images.githubusercontent.com/32491056/133228873-b069043e-4312-4ff1-a6dc-2e5e245135b5.png)

Is the ellipsis overflow okay?

**Comment by ddeboer** [comment]
Okay with me! @sdevalk?

**Comment by sdevalk** [comment]
> Okay with me! @sdevalk?

Perfect!
