### ISSUE TITLE
Instructions to run the presentation client are missing

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/solid-crs#476]
There is no documentation on how to run the presentation client on the data in a specific pod. Maybe add some help text when calling https://solid-crs-presentatie.netwerkdigitaalerfgoed.nl without (or with the wrong) parameters.

**Comment by lem-onade** [comment]
Hey @EnnoMeijers 

The easiest way to get into the presentation module is by appending the URL encoded WebID, followed by `/about`.

URL encoding can be done in your browser's console using `encodeURIComponent` or on a website like https://www.onlinewebtoolkit.com/url-encode-decode.

Example for WebID http://localhost:3000/hetlageland/profile/card#me: `https://solid-crs-presentatie.netwerkdigitaalerfgoed.nl/http%3A%2F%2Flocalhost%3A3000%2Fhetlageland%2Fprofile%2Fcard%23me/about`

**Comment by lem-onade** [comment]
Perhaps a WebID input could be shown when navigating to the root of the application, which does the URL encoding and construction for you.

@ddeboer What do you think?

**Comment by ddeboer** [comment]
Good idea @lem-onade! That also gives us a front page for the currently weirdly empty grey https://solid-crs-presentatie.netwerkdigitaalerfgoed.nl.

**Comment by EnnoMeijers** [comment]
Thanks for this for this info, I finally managed to load the data from my own pod, nice! A form to input the WebID would be very helpful indeed.

**Comment by lem-onade** [comment]
Great news! I've created https://github.com/netwerk-digitaal-erfgoed/solid-crs/issues/477 for the front page.
