### ISSUE TITLE
Adding local term: require a value

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/solid-crs#482]
I want to add my own term to an object's description. In the 'Network of Terms' view I click on 'Voeg een eigen term toe' and then click on the 'plus' sign. This causes my term to be added to the selected terms. However, I haven't filled in a value, so the listing of selected terms merely shows an entry with the word 'Eigen term'.

Is is possible to first check whether the 'eigen term' field has a value before adding it to the selected terms?

![Screenshot 2021-10-04 at 16 48 11](https://user-images.githubusercontent.com/606948/135873206-0cde6110-e8fe-4470-92e4-d63cd1d376fd.png)

**Comment by ddeboer** [comment]
Alternatively, prevent empty custom terms from being added to the list in the first place. We can do so by hiding the plus icon and disabling the enter key action until some term label has been entered in the text input.
