### ISSUE TITLE
Partial page when institution hasn't published its collections yet

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/solid-crs#490]
I want to see the collections and objects of an institution that uses Solid CRS via the presentation app.

I go to the institutions's app (using its WebID in the URL). A part of the page is rendered, but that's it. After a few seconds my browser - Firefox - warns me that 'this page is slowing down Firefox' (see screenshot). This is probably caused by the institutions's pod settings, which do not allow external viewers.

Is is possible to (a) show a meaningful message to the user (e.g. 'Deze instelling heeft nog geen collecties gepubliceerd') and (b) to prevent Firefox from showing the warning?

![Screenshot 2021-10-04 at 17 59 38](https://user-images.githubusercontent.com/606948/135884486-55711b61-d87e-4335-b266-160b5b0b2f07.png)

**Comment by lem-onade** [comment]
Also check settings access rights in solid-crs
