### ISSUE TITLE
Icon to go to the presentation application

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/solid-crs#522]
The manage application now has an [icon](https://github.com/netwerk-digitaal-erfgoed/solid-crs/pull/507) that you can click on to go to the presentation application - nice! Two remarks, however:

1. On the 'collections' page the icon is blue and a bit smaller, whereas the icon is black and a bit larger on the 'object' page. Is it possible to harmonize these?

<img width="171" alt="Screenshot 2021-11-19 at 07 41 22" src="https://user-images.githubusercontent.com/606948/142577169-4e3b9e23-9651-48d3-a9d9-d992cc38bb2a.png">
<img width="127" alt="Screenshot 2021-11-19 at 07 41 27" src="https://user-images.githubusercontent.com/606948/142577179-4d40ff6d-84f5-4784-8ae4-b0770d8e4024.png">

2. I'm not sure if the meaning of the icon is clear enough. The icon is commonly used for 'sharing' content, e.g. with some social platform. But we're not sharing content in our application. Would it make sense to use another icon instead, e.g. the one that we use for viewing the full size image of an object?

<img width="139" alt="Screenshot 2021-11-19 at 07 41 34" src="https://user-images.githubusercontent.com/606948/142577203-79deb775-f736-46bd-9c26-3a57a7a71b10.png">

**Comment by lem-onade** [comment]
hey @sdevalk, not sure what you mean with

> e.g. the one that we use for viewing the full size image of an object

I assume you had an icon like the following in mind?

![image](https://user-images.githubusercontent.com/32491056/144410206-3f372c30-2334-4abd-9360-3dd66a0f352c.png)

**Comment by sdevalk** [comment]
Hi @lem-onade 

> I assume you had an icon like the following in mind?

Actually, I was thinking of this one:

<img width="139" alt="Screenshot 2021-11-19 at 07 41 34" src="https://user-images.githubusercontent.com/606948/142577203-79deb775-f736-46bd-9c26-3a57a7a71b10.png">

We currently use this for linking to the full size image, but we could also use this for linking to the presentation app?

**Comment by ddeboer** [comment]
This is done.
