### ISSUE TITLE
WebID server

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/solid-crs#534]
Run a separate Community Solid Server for hosting the WebIDs and make it available at webid.netwerkdigitaalerfgoed.nl.

@lem-onade Should this container be based on the ghcr.io/netwerk-digitaal-erfgoed/solid-crs-pods, just like the pods server or do we need a separate image?

**Comment by lem-onade** [comment]
I think it's fine using the existing image, but we'll need to make some manual changes to the configuration. (disabling signup, login, adding access control rules for writes from id-proxy, ...) Most of this is one-time setup, with no need for automatic updates each release, so is it fine for you to manually update the new /config and /data volumes once?

Will leave another comment on this issue with the exact config.

**Comment by ddeboer** [comment]
The WebID server will definitely have its own data volume. However, in the current image, the config file is baked into that. So it is probably needed to create a separate `solid-crs-webid` image.

**Comment by lem-onade** [comment]
Alright, no problem, probably the wiser option. Allows for easier edits to the config if needed in the future.
