### ISSUE TITLE
UI is messed up for multi paged collections

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/solid-crs#535]
In both the management and presentation the UI shows javascript code and is messed up for collections that have multiple pages. See the Solvember collection in the "erfgoedinstelling" account: [management app](https://solid-crs.netwerkdigitaalerfgoed.nl/collection/https%3A%2F%2Fpod.inrupt.com%2Ferfgoedinstelling%2Fheritage-collections%2Fcatalog%23collection-ebf9631f-b66c-4a29-93d4-064b139e9763) and [presentation app](https://solid-crs-presentatie.netwerkdigitaalerfgoed.nl/https%3A%2F%2Fpod.inrupt.com%2Ferfgoedinstelling%2Fprofile%2Fcard%23me/collection/https%3A%2F%2Fpod.inrupt.com%2Ferfgoedinstelling%2Fheritage-collections%2Fcatalog%23collection-ebf9631f-b66c-4a29-93d4-064b139e9763).

**Comment by lem-onade** [comment]
On it, seems to only occur in safari
