### ISSUE TITLE
'404' error when clicking on back button

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/solid-crs#540]
Scenario: in the manage app I want to navigate between pages. I go to a collection, with an overview of objects. I then click on the card of one of the objects; the details of the object are presented. I then click on the back button, to go back to the collection again. However, then a '404' page is shown.

<img width="1041" alt="Screenshot 2021-12-17 at 07 04 55" src="https://user-images.githubusercontent.com/606948/146497236-01c54e0d-c5d4-4d10-9612-0ad24f289447.png">

**Comment by lem-onade** [comment]
Fixed in #543. Note that the routing is mostly to update the URL, going back/forward will probably always bring you back to your first collection.
