### ISSUE TITLE
Editing objects fails with call to localhost

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/solid-crs#555]
When editing https://solid-crs.netwerkdigitaalerfgoed.nl/object/https%3A%2F%2Fpods.netwerkdigitaalerfgoed.nl%2Faead6b8f-8f9a-5c83-9a32-9fde257e4276%2Fheritage-objects%2Fdata-5e151330-1069-49c6-9c8d-02ca52285cb4%23object-f04c43a1-39d3-4ae2-a209-01679a3bd62f:

```
POST http://localhost:3003/component/query net::ERR_CONNECTION_REFUSED
```

@lem-onade Why is the app trying to connect to localhost? Is this a configuration error?

**Comment by lem-onade** [comment]
indeed a mistake, seems the env variable was incorrectly overwritten in [.env.production](https://github.com/netwerk-digitaal-erfgoed/solid-crs/blob/develop/packages/solid-crs-manage/.env.production)
