### ISSUE TITLE
Bug: Broken link in de readme

### ISSUE THREAD

**Issue by mzeinstra** [netwerk-digitaal-erfgoed/solid-crs#605]
The installation guide link leads to a 404. 
This is
`xref:docs/modules/ROOT/pages/install.adoc`
but should be
`xref:docs/modules/manual/pages/install.adoc`

unfortunately I cannot create a pull request to fix it.

**Comment by EnnoMeijers** [comment]
Oeps, thnx Maarten for reporting this, I adjusted the link. Nice to see you are interested! If you have any feedback or suggestions please let us know.
